services:
  - type: web
    name: trainmate
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: WEB_CONCURRENCY
        value: "1"
      - key: DEMO_USERNAME
        value: user
      - key: DEMO_PASSWORD
        sync: false
