# Generated by Django 6.1.1 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0006_visiondevice_visionanalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="visionanalysis",
            name="snapshot",
            field=models.FileField(
                blank=True,
                help_text="An optional user-approved progress frame from the Pi.",
                upload_to="vision_snapshots/%Y/%m/%d",
            ),
        ),
    ]
