# Generated by Django 6.1.1 on 2026-09-16 14:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_visionanalysis_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('weekdays', models.JSONField(default=list)),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ('capacity', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('location', models.CharField(max_length=200)),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.specialization')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.trainer')),
            ],
            options={
                'ordering': ['trainer__name', 'title', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='recurring_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='training.recurringschedule'),
        ),
    ]
