# Generated by Django 6.1.1 on 2026-09-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_recurringschedule_trainingsession_recurring_schedule'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trainingsession',
            constraint=models.UniqueConstraint(fields=('recurring_schedule', 'starts_at'), name='unique_recurring_schedule_occurrence'),
        ),
    ]
