# Generated by Django 6.1.1 on 2026-09-16 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_trainingsession_unique_recurring_schedule_occurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('trainer', 'Trainer'), ('kiosk', 'Reception kiosk')], default='client', max_length=10),
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('attended', 'Attended'), ('absent', 'Absent'), ('cancelled', 'Cancelled')], default='booked', max_length=10)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='training.trainingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('session', 'user'), name='unique_session_attendance')],
            },
        ),
    ]
