# Generated by Django 6.1.1 on 2026-09-16 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_alter_user_role_sessionattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='training.trainer')),
            ],
            options={
                'ordering': ['-paid_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='salaryaccrual',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accruals', to='training.trainerpayout'),
        ),
    ]
