# Generated by Django 6.1.1 on 2026-09-16 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_trainerpayout_salaryaccrual_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerpayout',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank transfer'), ('unknown', 'Not recorded')], default='unknown', max_length=12),
        ),
        migrations.AddField(
            model_name='trainerpayout',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salaryaccrual',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='salary_accrual', to='training.trainingsession'),
        ),
        migrations.AlterField(
            model_name='salaryaccrual',
            name='status',
            field=models.CharField(choices=[('accrued', 'Expected'), ('ready', 'Ready for payout'), ('paid', 'Paid')], default='accrued', max_length=10),
        ),
    ]
